name: APPROVE
 
on: pull_request # run on pull request events
 
permissions:
 pull-requests: write # grant write permission on the pull-requests endpoint
jobs:
  dump-env:
    runs-on: ubuntu-latest
    steps:
      - name: Print all env vars
        run: |
          env
